name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Give permission
        run: chmod +x gradlew

      - name: Start application
        run: java -jar ./artifacts/app-mbank.jar &

      - name: Wait for app
        run: sleep 15

      - name: Run tests
        run: ./gradlew test